package common.html;

import java.io.FileWriter;

import common.base.Logger;

/**
 * An HTML page.
 *
 * <p><b>Modifications:</b>
 * <ul>
 * <li>04.02.2023: nicz - Creation</li>
 * </ul>
 */
public class HtmlPage {
	private static final Logger log = new Logger("HtmlPage", true);
	private String sTitle;
	private String sFilename;
	private String sCss;
	private final HtmlTag html;
	private final HtmlTag main;
	
	public HtmlPage(String sTitle, String sFilename, String sCss) {
		this.sTitle = sTitle;
		this.sFilename = sFilename;
		this.sCss = sCss;
		this.html = new HtmlTag("html");
		this.main = new DivHtmlTag("main");
		buildHead();
		buildBody();
	}
	
	public void add(HtmlTag tag) {
		this.main.addTag(tag);
	}
	
	public void save() {
		log.info("Saving " + sFilename);
		try {
			FileWriter fw = new FileWriter(sFilename);
			fw.write("<!DOCTYPE html>");
			fw.write(html.toHtml(0, false));
			fw.close();
		} catch (Exception exc) {
			log.error("Saving document failed: " + exc.getMessage());
		}
	}
	
	protected void buildHead() {
		HtmlTag head = new HtmlTag("head");
		head.addTag(HtmlTagFactory.comment("Generated by testHtmlPage.java"));
		head.addTag(new HtmlTag("title", sTitle));
		HtmlTag tagCss = new HtmlTag("link");
		tagCss.addAttribute("rel", "stylesheet");
		tagCss.addAttribute("type", "text/css");
		tagCss.addAttribute("href", this.sCss);
		head.addTag(tagCss);
		html.addTag(head);
	}
	
	protected void buildBody() {
		HtmlTag body = new HtmlTag("body");
		body.addTag(main);
		html.addTag(body);
	}

	private static void testHtmlPage() {
		log.info("Testing HtmlPage");
		final String sFilename = "/home/nicz/www/test/test.html";
		final String css = "../scripts/style.css";
		HtmlPage test = new HtmlPage("Test", sFilename, css);
		test.add(HtmlTagFactory.title(1, "HtmlPage test"));

		// Test list
		test.add(HtmlTagFactory.title(2, "List test"));
		ListHtmlTag list = new ListHtmlTag();
		for (int i=0; i<4; ++i) {
			list.addItem("item " + (i+1));
		}
		test.add(list);
		
		// Test table
		test.add(HtmlTagFactory.title(2, "Table test"));
		TableHtmlTag table = new TableHtmlTag(4);
		for (int i=0; i<11; ++i) {
			table.addCell("cell " + (i+1));
		}
		test.add(table);
		
		// Test links
		test.add(HtmlTagFactory.title(2, "Link test"));
		test.add(HtmlTagFactory.link("http://www.google.com", "Google"));
		test.add(HtmlTagFactory.link("../recettes/index.html", "Recettes"));
		
		// Test images
		test.add(HtmlTagFactory.title(2, "Image test"));
		String src = "../../prog/python/Orfact/images/RandomImage00.png";
		test.add(HtmlTagFactory.image(src, "Orfact random image"));
		
		test.save();
	}
	
	/**
	 * Testing method
	 * @param args  unused
	 */
	public static void main(String[] args) {
		testHtmlPage();
	}
}